version: '3.8'

services:
  # FastAPI Application
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - DATABASE_URL=sqlite:///./carrier_agent.db
      - FMCSA_API_KEY=${FMCSA_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - DEBUG=False
      - PORT=8000
    volumes:
      - ./logs:/app/logs
      - ./carrier_agent.db:/app/carrier_agent.db  # Persist SQLite database
    restart: unless-stopped
    networks:
      - carrier-network

  # Nginx reverse proxy (for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./infra/ssl:/etc/nginx/ssl
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - carrier-network
    profiles:
      - production

networks:
  carrier-network:
    driver: bridge